language: rust
sudo: false

# Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
cache:
  directories:
    - /home/travis/.cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

matrix:
  allow_failures:
    - name: Tests
  include:
    - name: Page
      rust: stable
      before_script:
        - rustup target add wasm32-unknown-unknown
      script:
        - cargo build --target wasm32-unknown-unknown --release
        - cp target/wasm32-unknown-unknown/release/sudoku-bin.wasm www/
        - cp -r assets/ www/
      deploy:
        provider: pages
        local_dir: deploy
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true

    - name: Tests
      env: RUST_BACKTRACE=1
      rust: stable
      addons:
        firefox: latest
        chrome: stable
      script:
        - cargo test --all
        - cargo test --all --target wasm32-unknown-unknown


notifications:
  email:
    on_success: never